name: PDNPR
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - networkx
  - tk
  - tqdm
  - mdtraj
  - pymol-open-source
  - pip:
      - contourpy==1.2.1
      - cycler==0.12.1
      - fonttools==4.51.0
      - kiwisolver==1.4.5
      - matplotlib==3.9.0
      - pillow==10.3.0
